# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('birthdate', models.DateField(verbose_name='Date of birth')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('contacts', models.IntegerField(verbose_name='Contacts')),
                ('jabber_id', models.PositiveIntegerField(verbose_name='Jabber: JID')),
                ('skype_id', models.PositiveIntegerField(verbose_name='Skype: id')),
                ('other_contacts', models.TextField(verbose_name='Other Contacts')),
            ],
        ),
    ]
