# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='jabber_id',
            field=models.CharField(max_length=128, verbose_name='Jabber: JID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='skype_id',
            field=models.CharField(max_length=256, verbose_name='Skype: id'),
        ),
    ]
